name: Restrict Merges to Main

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is not from develop
        run: |
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "❌ Merge only allowed from develop"
            exit 1
          fi
